package io.spia.processor

import io.spia.processor.model.*
import io.spia.processor.model.SealedSubtype

class TypeScriptGenerator(private val config: SdkConfig) {

    fun generate(controllers: List<ControllerInfo>, typeResolver: TypeResolver): String {
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by SPIA — do not edit manually.")
        sb.appendLine()

        // Axios import
        if (config.apiClient == ApiClient.AXIOS) {
            sb.appendLine("import type { AxiosInstance } from 'axios';")
            sb.appendLine()
        }

        // ApiError base class — always emitted
        sb.appendLine("/* ──────────── Error Types ──────────── */")
        sb.appendLine()
        sb.appendLine("export class ApiError<T = unknown> extends Error {")
        sb.appendLine("  constructor(public status: number, public data: T, message?: string) { super(message); }")
        sb.appendLine("}")
        sb.appendLine()

        // DTO types section
        val dtos = typeResolver.allDtos()
        val enums = typeResolver.allEnums()
        val generics = typeResolver.allGenerics()
        val sealedUnions = typeResolver.allSealedUnions()

        if (dtos.isNotEmpty() || enums.isNotEmpty() || generics.isNotEmpty() || sealedUnions.isNotEmpty()) {
            sb.appendLine("/* ──────────── DTO Types ──────────── */")
            sb.appendLine()
        }

        for (enumInfo in enums.sortedBy { it.name }) {
            sb.append(renderEnum(enumInfo))
            sb.appendLine()
        }

        // Sealed union subtype DTOs are emitted individually (interfaces), then the union type alias.
        // Track which DTO names were already emitted as part of a sealed union so we skip them in
        // the flat DTO loop (they may also have been registered in resolvedDtos by the resolver).
        val sealedSubtypeDtoNames = sealedUnions.flatMap { it.subtypes.map { s -> s.dto.name } }.toSet()

        for (sealedUnion in sealedUnions.sortedBy { it.name }) {
            sb.append(renderSealedUnion(sealedUnion))
            sb.appendLine()
        }

        for (dto in dtos.filter { it.name !in sealedSubtypeDtoNames }.sortedBy { it.name }) {
            sb.append(renderDto(dto))
            sb.appendLine()
        }

        for (generic in generics.sortedBy { it.name }) {
            sb.append(renderGenericInterface(generic))
            sb.appendLine()
        }

        // Per-endpoint typed error aliases
        val errorAliases = buildList {
            for (controller in controllers.sortedBy { it.name }) {
                for (endpoint in controller.endpoints) {
                    val errorTypes = endpoint.errorResponses.values.toList()
                    if (errorTypes.isEmpty()) continue
                    val aliasName = endpoint.functionName.replaceFirstChar { it.uppercase() } + "Error"
                    val unionTs = if (errorTypes.size == 1) {
                        renderType(errorTypes.first())
                    } else {
                        errorTypes.joinToString(" | ") { renderType(it) }
                    }
                    add("export type $aliasName = ApiError<$unionTs>;")
                }
            }
        }
        if (errorAliases.isNotEmpty()) {
            sb.appendLine("/* ──────────── Endpoint Error Aliases ──────────── */")
            sb.appendLine()
            errorAliases.forEach { sb.appendLine(it) }
            sb.appendLine()
        }

        // API functions section
        if (controllers.isNotEmpty()) {
            sb.appendLine("/* ──────────── API Functions ──────────── */")
            sb.appendLine()
            sb.append(renderCreateApi(controllers))
        }

        return sb.toString()
    }

    private fun renderEnum(enumInfo: TypeInfo.Enum): String {
        val sb = StringBuilder()
        when (config.enumStyle) {
            EnumStyle.UNION -> {
                val members = enumInfo.constants.joinToString(" | ") { "'$it'" }
                sb.appendLine("export type ${enumInfo.name} = $members;")
            }
            EnumStyle.ENUM -> {
                sb.appendLine("export enum ${enumInfo.name} {")
                for (constant in enumInfo.constants) {
                    sb.appendLine("  $constant = \"$constant\",")
                }
                sb.appendLine("}")
            }
        }
        return sb.toString()
    }

    private fun renderDto(dto: TypeInfo.Dto): String {
        val sb = StringBuilder()
        sb.appendLine("export interface ${dto.name} {")
        for (field in dto.fields) {
            renderField(sb, field)
        }
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderSealedUnion(sealedUnion: TypeInfo.SealedUnion): String {
        val sb = StringBuilder()
        // First emit each subtype's interface definition.
        for (subtype in sealedUnion.subtypes) {
            sb.append(renderDto(subtype.dto))
        }
        // Then emit the union type alias.
        if (sealedUnion.discriminator != null) {
            // Discriminated union: each member is intersected with the literal discriminator object.
            val members = sealedUnion.subtypes.joinToString(" | ") { st ->
                val tag = st.tag ?: st.dto.name
                "({ ${sealedUnion.discriminator}: '${tag}' } & ${st.dto.name})"
            }
            sb.appendLine("export type ${sealedUnion.name} = $members;")
        } else {
            // Nominal union: simple A | B | C without discriminator literals.
            val members = sealedUnion.subtypes.joinToString(" | ") { it.dto.name }
            sb.appendLine("export type ${sealedUnion.name} = $members;")
        }
        return sb.toString()
    }

    private fun renderField(sb: StringBuilder, field: FieldInfo) {
        if (field.aliases.isNotEmpty()) {
            sb.appendLine("  /** @alias ${field.aliases.joinToString(", ")} */")
        }
        val tsType = renderType(field.type)
        val fieldName = field.serializedName
        when {
            field.type.nullable && field.excludeWhenNull -> sb.appendLine("  $fieldName?: $tsType | null;")
            field.type.nullable -> sb.appendLine("  $fieldName: $tsType | null;")
            else -> sb.appendLine("  $fieldName: $tsType;")
        }
    }

    private fun renderType(type: TypeInfo): String = when (type) {
        is TypeInfo.Primitive -> type.tsType
        is TypeInfo.Array -> "${renderType(type.elementType)}[]"
        is TypeInfo.Record -> {
            val key = renderType(type.keyType)
            val value = renderType(type.valueType)
            "{ [key: $key]: $value }"
        }
        is TypeInfo.Enum -> type.name
        is TypeInfo.Dto -> type.name
        is TypeInfo.Unknown -> type.rawName
        is TypeInfo.Generic -> {
            if (type.typeArguments.isEmpty()) {
                // Raw reference (shouldn't normally happen at usage site, but keep safe).
                "${type.name}<${type.typeParameters.joinToString(", ")}>"
            } else {
                "${type.name}<${type.typeArguments.joinToString(", ") { renderType(it) }}>"
            }
        }
        is TypeInfo.TypeParameter -> type.name
        is TypeInfo.SealedUnion -> type.name
    }

    private fun renderGenericInterface(generic: TypeInfo.Generic): String {
        val sb = StringBuilder()
        val params = generic.typeParameters.joinToString(", ")
        sb.appendLine("export interface ${generic.name}<$params> {")
        for (field in generic.fields) {
            renderField(sb, field)
        }
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderCreateApi(controllers: List<ControllerInfo>): String {
        val sb = StringBuilder()

        val clientParam = when (config.apiClient) {
            ApiClient.AXIOS -> "client: AxiosInstance"
            ApiClient.FETCH -> {
                sb.appendLine("export interface ClientOptions {")
                sb.appendLine("  baseUrl?: string;")
                sb.appendLine("}")
                sb.appendLine()
                "options?: ClientOptions"
            }
        }

        sb.appendLine("export function createApi($clientParam) {")
        if (config.apiClient == ApiClient.FETCH) {
            val buildtimeBase = config.baseUrl?.let { "\"${it}\"" } ?: "\"\""
            sb.appendLine("  const _baseUrl = options?.baseUrl ?? $buildtimeBase;")
        }
        sb.appendLine("  return {")

        for (controller in controllers.sortedBy { it.name }) {
            val namespace = controllerToNamespace(controller.name)
            sb.appendLine("    $namespace: {")

            for (endpoint in controller.endpoints) {
                val fullPath = combinePaths(controller.basePath, endpoint.path)
                sb.append(renderEndpoint(endpoint, fullPath))
            }

            sb.appendLine("    },")
        }

        sb.appendLine("  };")
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderEndpoint(endpoint: EndpointInfo, fullPath: String): String {
        val sb = StringBuilder()

        // Build a JSDoc block combining the source docstring and any @param @default notes
        // for optional @RequestParam values. A non-null defaultValue is Spring's source of
        // truth — we preserve it here without baking it into the SDK signature.
        val jsdocLines = mutableListOf<String>()
        endpoint.jsdoc?.let { jsdocLines += it }
        endpoint.parameters.filter { it.defaultValue != null }.forEach { p ->
            jsdocLines += "@param {${renderType(p.type)}} [${p.name}=${p.defaultValue}] Server default: ${p.defaultValue}"
        }
        if (jsdocLines.isNotEmpty()) {
            sb.appendLine("      /**")
            jsdocLines.forEach { sb.appendLine("       * $it") }
            sb.appendLine("       */")
        }

        val params = renderEndpointParams(endpoint)
        val tsPath = renderEndpointUrl(endpoint, fullPath)
        val promiseType = renderEndpointReturn(endpoint)

        sb.append(renderEndpointCall(endpoint, fullPath, params, tsPath, promiseType, config))

        sb.appendLine()
        return sb.toString()
    }

    /** Builds the TypeScript parameter signature string. */
    private fun renderEndpointParams(endpoint: EndpointInfo): String {
        // Parameter list — optional query params get a TS-level `?` marker so callers
        // may omit them; fetch/axios builders will skip undefined values below.
        // MULTIPART params get File | Blob (single) or (File | Blob)[] (list) types.
        return endpoint.parameters.joinToString(", ") { param ->
            val marker = if (param.kind == ParameterKind.QUERY && !param.required) "?" else ""
            val tsType = if (param.kind == ParameterKind.MULTIPART) {
                if (param.type is TypeInfo.Array) "(File | Blob)[]" else "File | Blob"
            } else {
                renderType(param.type)
            }
            "${param.name}$marker: $tsType"
        }
    }

    /** Assembles the axios-style URL template literal with path variable substitutions. */
    private fun renderEndpointUrl(endpoint: EndpointInfo, fullPath: String): String {
        val pathVariables = endpoint.parameters.filter { it.kind == ParameterKind.PATH }
        return buildTsPath(fullPath, pathVariables)
    }

    /** Emits the axios or fetch call line(s) for the endpoint. */
    private fun renderEndpointCall(
        endpoint: EndpointInfo,
        fullPath: String,
        params: String,
        tsPath: String,
        promiseType: String,
        config: SdkConfig,
    ): String {
        val sb = StringBuilder()
        val multipartParams = endpoint.parameters.filter { it.kind == ParameterKind.MULTIPART }
        val bodyParam = endpoint.parameters.firstOrNull { it.kind == ParameterKind.BODY }
        val queryParams = endpoint.parameters.filter { it.kind == ParameterKind.QUERY }
        val headerParams = endpoint.parameters.filter { it.kind == ParameterKind.HEADER }

        when (config.apiClient) {
            ApiClient.AXIOS -> {
                if (multipartParams.isNotEmpty()) {
                    // Multipart: emit function body with FormData construction
                    sb.append("      ${endpoint.functionName}: async ($params): Promise<$promiseType> => {\n")
                    sb.appendLine("        const formData = new FormData();")
                    for (mp in multipartParams) {
                        val fieldName = mp.headerName ?: mp.name
                        if (mp.type is TypeInfo.Array) {
                            sb.appendLine("        ${mp.name}.forEach(f => formData.append('$fieldName', f));")
                        } else {
                            sb.appendLine("        formData.append('$fieldName', ${mp.name});")
                        }
                    }
                    val axiosConfig = buildAxiosConfig(queryParams, headerParams)
                    sb.appendLine("        return client.${endpoint.httpMethod.name.lowercase()}($tsPath, formData$axiosConfig).then(r => r.data);")
                    sb.appendLine("      },")
                } else {
                    sb.append("      ${endpoint.functionName}: ($params): Promise<$promiseType> =>\n")
                    val axiosConfig = buildAxiosConfig(queryParams, headerParams)
                    when (endpoint.httpMethod) {
                        HttpMethod.GET, HttpMethod.DELETE -> {
                            sb.appendLine("        client.${endpoint.httpMethod.name.lowercase()}($tsPath$axiosConfig).then(r => r.data),")
                        }
                        HttpMethod.POST, HttpMethod.PUT, HttpMethod.PATCH -> {
                            val bodyArg = bodyParam?.name ?: "undefined"
                            sb.appendLine("        client.${endpoint.httpMethod.name.lowercase()}($tsPath, $bodyArg$axiosConfig).then(r => r.data),")
                        }
                    }
                }
            }
            ApiClient.FETCH -> {
                sb.append("      ${endpoint.functionName}: async ($params): Promise<$promiseType> => {\n")
                val (queryPrelude, queryFragment) = buildFetchQuery(queryParams)
                val pathVariables = endpoint.parameters.filter { it.kind == ParameterKind.PATH }
                val fetchPathBase = buildFetchPath(fullPath, pathVariables)
                // Drop the trailing backtick, append the query fragment, re-close the template literal.
                val fetchUrl = if (queryFragment.isNotEmpty()) {
                    fetchPathBase.trimEnd('`') + queryFragment + "`"
                } else fetchPathBase

                for (line in queryPrelude) {
                    sb.appendLine("        $line")
                }

                if (multipartParams.isNotEmpty()) {
                    // Multipart: build FormData and use as body (no Content-Type — browser sets boundary)
                    sb.appendLine("        const formData = new FormData();")
                    for (mp in multipartParams) {
                        val fieldName = mp.headerName ?: mp.name
                        if (mp.type is TypeInfo.Array) {
                            sb.appendLine("        ${mp.name}.forEach(f => formData.append('$fieldName', f));")
                        } else {
                            sb.appendLine("        formData.append('$fieldName', ${mp.name});")
                        }
                    }
                    if (headerParams.isNotEmpty()) {
                        val headerEntries = headerParams.joinToString(", ") { p ->
                            val key = p.headerName ?: p.name
                            "'$key': ${p.name}"
                        }
                        sb.appendLine("        const res = await fetch($fetchUrl, { method: '${endpoint.httpMethod.name}', headers: { $headerEntries }, body: formData });")
                    } else {
                        sb.appendLine("        const res = await fetch($fetchUrl, { method: '${endpoint.httpMethod.name}', body: formData });")
                    }
                } else {
                    when (endpoint.httpMethod) {
                        HttpMethod.GET, HttpMethod.DELETE -> {
                            if (headerParams.isNotEmpty()) {
                                val headerEntries = headerParams.joinToString(", ") { p ->
                                    val key = p.headerName ?: p.name
                                    "'$key': ${p.name}"
                                }
                                sb.appendLine("        const res = await fetch($fetchUrl, { method: '${endpoint.httpMethod.name}', headers: { $headerEntries } });")
                            } else {
                                sb.appendLine("        const res = await fetch($fetchUrl, { method: '${endpoint.httpMethod.name}' });")
                            }
                        }
                        HttpMethod.POST, HttpMethod.PUT, HttpMethod.PATCH -> {
                            val bodyArg = bodyParam?.name ?: "undefined"
                            if (headerParams.isNotEmpty()) {
                                val headerEntries = headerParams.joinToString(", ") { p ->
                                    val key = p.headerName ?: p.name
                                    "'$key': ${p.name}"
                                }
                                sb.appendLine("        const res = await fetch($fetchUrl, { method: '${endpoint.httpMethod.name}', headers: { 'Content-Type': 'application/json', $headerEntries }, body: JSON.stringify($bodyArg) });")
                            } else {
                                sb.appendLine("        const res = await fetch($fetchUrl, { method: '${endpoint.httpMethod.name}', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify($bodyArg) });")
                            }
                        }
                    }
                }
                sb.appendLine("        if (!res.ok) throw new ApiError(res.status, await res.json(), `SPIA ${endpoint.httpMethod.name} \${res.url} failed: \${res.status} \${res.statusText}`);")
                if (promiseType != "void") {
                    sb.appendLine("        return res.json();")
                }
                sb.appendLine("      },")
            }
        }
        return sb.toString()
    }

    /** Returns the Promise return type string for the endpoint. */
    private fun renderEndpointReturn(endpoint: EndpointInfo): String {
        val returnTs = renderType(endpoint.returnType)
        return if (returnTs == "void") "void" else returnTs
    }

    private fun buildTsPath(path: String, pathVariables: List<ParameterInfo>): String {
        if (pathVariables.isEmpty()) return "`$path`"
        var tsPath = path
        for (pv in pathVariables) {
            tsPath = Regex("\\{${Regex.escape(pv.name)}(?::[^}]+)?\\}").replace(tsPath) {
                "\${encodeURIComponent(String(${pv.name}))}"
            }
        }
        return "`$tsPath`"
    }

    private fun buildFetchPath(path: String, pathVariables: List<ParameterInfo>): String {
        var tsPath = path
        for (pv in pathVariables) {
            tsPath = Regex("\\{${Regex.escape(pv.name)}(?::[^}]+)?\\}").replace(tsPath) {
                "\${encodeURIComponent(String(${pv.name}))}"
            }
        }
        return "`\${_baseUrl}$tsPath`"
    }

    private fun buildAxiosConfig(queryParams: List<ParameterInfo>, headerParams: List<ParameterInfo>): String {
        // axios serializes the params object itself — no manual encoding needed here.
        // Optional params are spread conditionally so an explicit `undefined` is dropped
        // from the outgoing query entirely rather than serialized as "undefined".
        val parts = mutableListOf<String>()
        if (queryParams.isNotEmpty()) {
            val queryParts = queryParams.joinToString(", ") { p ->
                if (p.required) "${p.name}: ${p.name}"
                else "...(${p.name} !== undefined ? { ${p.name}: ${p.name} } : {})"
            }
            parts.add("params: { $queryParts }")
        }
        if (headerParams.isNotEmpty()) {
            val headerEntries = headerParams.joinToString(", ") { p ->
                val key = p.headerName ?: p.name
                "'$key': ${p.name}"
            }
            parts.add("headers: { $headerEntries }")
        }
        if (parts.isEmpty()) return ""
        return ", { ${parts.joinToString(", ")} }"
    }

    /**
     * Returns (preludeLines, urlFragment) for the fetch query string.
     * - No params: empty list + empty fragment.
     * - All required: inline `?k=${encodeURIComponent(...)}&...` fragment, no prelude.
     * - Has optional: emit `const params = new URLSearchParams(); …; const qs = params.toString();`
     *   as prelude and use `${qs ? `?${qs}` : ''}` as the fragment so all-undefined calls
     *   produce a clean URL with no trailing `?`.
     */
    private fun buildFetchQuery(queryParams: List<ParameterInfo>): Pair<List<String>, String> {
        if (queryParams.isEmpty()) return emptyList<String>() to ""
        val hasOptional = queryParams.any { !it.required }
        if (!hasOptional) {
            val inline = queryParams.joinToString("&") {
                "${encodeURIComponentLiteral(it.name)}=\${encodeURIComponent(String(${it.name}))}"
            }
            return emptyList<String>() to "?$inline"
        }
        val prelude = buildList {
            add("const params = new URLSearchParams();")
            queryParams.forEach { p ->
                if (p.required) {
                    add("params.append('${p.name}', String(${p.name}));")
                } else {
                    add("if (${p.name} !== undefined) params.append('${p.name}', String(${p.name}));")
                }
            }
            add("const qs = params.toString();")
        }
        return prelude to "\${qs ? `?\${qs}` : ''}"
    }

    private fun encodeURIComponentLiteral(name: String): String =
        java.net.URLEncoder.encode(name, Charsets.UTF_8)
            .replace("+", "%20")

    private fun combinePaths(base: String, path: String): String {
        val normalizedBase = base.trimEnd('/')
        val normalizedPath = path.trimStart('/')
        return if (normalizedPath.isEmpty()) normalizedBase
        else "$normalizedBase/$normalizedPath"
    }

    private fun controllerToNamespace(controllerName: String): String {
        val name = controllerName.removeSuffix("Controller")
        return name.replaceFirstChar { it.lowercase() }
    }
}
