package io.spia.processor

import io.spia.processor.model.*

class TypeScriptGenerator(private val config: SdkConfig) {

    fun generate(controllers: List<ControllerInfo>, typeResolver: TypeResolver): String {
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by SPIA — do not edit manually.")
        sb.appendLine()

        // Axios import
        if (config.apiClient == ApiClient.AXIOS) {
            sb.appendLine("import type { AxiosInstance } from 'axios';")
            sb.appendLine()
        }

        // DTO types section
        val dtos = typeResolver.allDtos()
        val enums = typeResolver.allEnums()

        if (dtos.isNotEmpty() || enums.isNotEmpty()) {
            sb.appendLine("/* ──────────── DTO Types ──────────── */")
            sb.appendLine()
        }

        for (enumInfo in enums.sortedBy { it.name }) {
            sb.append(renderEnum(enumInfo))
            sb.appendLine()
        }

        for (dto in dtos.sortedBy { it.name }) {
            sb.append(renderDto(dto))
            sb.appendLine()
        }

        // API functions section
        if (controllers.isNotEmpty()) {
            sb.appendLine("/* ──────────── API Functions ──────────── */")
            sb.appendLine()
            sb.append(renderCreateApi(controllers))
        }

        return sb.toString()
    }

    private fun renderEnum(enumInfo: TypeInfo.Enum): String {
        val sb = StringBuilder()
        when (config.enumStyle) {
            EnumStyle.UNION -> {
                val members = enumInfo.constants.joinToString(" | ") { "'$it'" }
                sb.appendLine("export type ${enumInfo.name} = $members;")
            }
            EnumStyle.ENUM -> {
                sb.appendLine("export enum ${enumInfo.name} {")
                for (constant in enumInfo.constants) {
                    sb.appendLine("  $constant = \"$constant\",")
                }
                sb.appendLine("}")
            }
        }
        return sb.toString()
    }

    private fun renderDto(dto: TypeInfo.Dto): String {
        val sb = StringBuilder()
        sb.appendLine("export interface ${dto.name} {")
        for (field in dto.fields) {
            val tsType = renderType(field.type)
            if (field.type.nullable) {
                sb.appendLine("  ${field.name}: $tsType | null;")
            } else {
                sb.appendLine("  ${field.name}: $tsType;")
            }
        }
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderType(type: TypeInfo): String = when (type) {
        is TypeInfo.Primitive -> type.tsType
        is TypeInfo.Array -> "${renderType(type.elementType)}[]"
        is TypeInfo.Record -> {
            val key = renderType(type.keyType)
            val value = renderType(type.valueType)
            "{ [key: $key]: $value }"
        }
        is TypeInfo.Enum -> type.name
        is TypeInfo.Dto -> type.name
        is TypeInfo.Unknown -> type.rawName
    }

    private fun renderCreateApi(controllers: List<ControllerInfo>): String {
        val sb = StringBuilder()

        val clientParam = when (config.apiClient) {
            ApiClient.AXIOS -> "client: AxiosInstance"
            ApiClient.FETCH -> "baseUrl: string"
        }

        sb.appendLine("export function createApi($clientParam) {")
        sb.appendLine("  return {")

        for (controller in controllers.sortedBy { it.name }) {
            val namespace = controllerToNamespace(controller.name)
            sb.appendLine("    $namespace: {")

            for (endpoint in controller.endpoints) {
                val fullPath = combinePaths(controller.basePath, endpoint.path)
                sb.append(renderEndpoint(endpoint, fullPath))
            }

            sb.appendLine("    },")
        }

        sb.appendLine("  };")
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderEndpoint(endpoint: EndpointInfo, fullPath: String): String {
        val sb = StringBuilder()

        // JSDoc
        if (endpoint.jsdoc != null) {
            sb.appendLine("      /** ${endpoint.jsdoc} */")
        }

        // Parameter list
        val params = endpoint.parameters.joinToString(", ") { param ->
            "${param.name}: ${renderType(param.type)}"
        }

        // Return type
        val returnTs = renderType(endpoint.returnType)
        val promiseType = if (returnTs == "void") "void" else returnTs

        // Build path with template literals for path variables
        val pathVariables = endpoint.parameters.filter { it.kind == ParameterKind.PATH }
        val tsPath = buildTsPath(fullPath, pathVariables)

        // Body parameter
        val bodyParam = endpoint.parameters.firstOrNull { it.kind == ParameterKind.BODY }

        // Query parameters
        val queryParams = endpoint.parameters.filter { it.kind == ParameterKind.QUERY }

        when (config.apiClient) {
            ApiClient.AXIOS -> {
                sb.append("      ${endpoint.functionName}: ($params): Promise<$promiseType> =>\n")
                val axiosConfig = buildAxiosConfig(queryParams)
                when (endpoint.httpMethod) {
                    HttpMethod.GET, HttpMethod.DELETE -> {
                        sb.appendLine("        client.${endpoint.httpMethod.name.lowercase()}($tsPath$axiosConfig).then(r => r.data),")
                    }
                    HttpMethod.POST, HttpMethod.PUT, HttpMethod.PATCH -> {
                        val bodyArg = bodyParam?.name ?: "undefined"
                        sb.appendLine("        client.${endpoint.httpMethod.name.lowercase()}($tsPath, $bodyArg$axiosConfig).then(r => r.data),")
                    }
                }
            }
            ApiClient.FETCH -> {
                sb.append("      ${endpoint.functionName}: async ($params): Promise<$promiseType> => {\n")
                val queryString = buildFetchQueryString(queryParams)
                val fetchPathBase = buildFetchPath(fullPath, pathVariables)
                // Drop the trailing backtick, append the query fragment, re-close the template literal.
                val fetchUrl = if (queryString.isNotEmpty()) {
                    fetchPathBase.trimEnd('`') + queryString + "`"
                } else fetchPathBase

                when (endpoint.httpMethod) {
                    HttpMethod.GET, HttpMethod.DELETE -> {
                        sb.appendLine("        const res = await fetch($fetchUrl, { method: '${endpoint.httpMethod.name}' });")
                    }
                    HttpMethod.POST, HttpMethod.PUT, HttpMethod.PATCH -> {
                        val bodyArg = bodyParam?.name ?: "undefined"
                        sb.appendLine("        const res = await fetch($fetchUrl, { method: '${endpoint.httpMethod.name}', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify($bodyArg) });")
                    }
                }
                if (promiseType != "void") {
                    sb.appendLine("        return res.json();")
                }
                sb.appendLine("      },")
            }
        }

        sb.appendLine()
        return sb.toString()
    }

    private fun buildTsPath(path: String, pathVariables: List<ParameterInfo>): String {
        if (pathVariables.isEmpty()) return "`$path`"
        var tsPath = path
        for (pv in pathVariables) {
            tsPath = tsPath.replace("{${pv.name}}", "\${encodeURIComponent(String(${pv.name}))}")
        }
        return "`$tsPath`"
    }

    private fun buildFetchPath(path: String, pathVariables: List<ParameterInfo>): String {
        var tsPath = path
        for (pv in pathVariables) {
            tsPath = tsPath.replace("{${pv.name}}", "\${encodeURIComponent(String(${pv.name}))}")
        }
        return "`\${baseUrl}$tsPath`"
    }

    private fun buildAxiosConfig(queryParams: List<ParameterInfo>): String {
        // axios serializes the params object itself — no manual encoding needed here.
        if (queryParams.isEmpty()) return ""
        val params = queryParams.joinToString(", ") { "${it.name}: ${it.name}" }
        return ", { params: { $params } }"
    }

    private fun buildFetchQueryString(queryParams: List<ParameterInfo>): String {
        if (queryParams.isEmpty()) return ""
        val params = queryParams.joinToString("&") {
            "${encodeURIComponentLiteral(it.name)}=\${encodeURIComponent(String(${it.name}))}"
        }
        return "?$params"
    }

    private fun encodeURIComponentLiteral(name: String): String =
        java.net.URLEncoder.encode(name, Charsets.UTF_8)
            .replace("+", "%20")

    private fun combinePaths(base: String, path: String): String {
        val normalizedBase = base.trimEnd('/')
        val normalizedPath = path.trimStart('/')
        return if (normalizedPath.isEmpty()) normalizedBase
        else "$normalizedBase/$normalizedPath"
    }

    private fun controllerToNamespace(controllerName: String): String {
        val name = controllerName.removeSuffix("Controller")
        return name.replaceFirstChar { it.lowercase() }
    }
}
