package io.spia.processor

import com.google.devtools.ksp.processing.KSPLogger
import io.spia.processor.model.*
import io.spia.processor.model.SealedSubtype

class TypeScriptGenerator(private val config: SdkConfig, private val logger: KSPLogger? = null) {

    // TypeResolver instance valid for the duration of the current generate() call.
    private var typeResolver: TypeResolver? = null

    fun generate(controllers: List<ControllerInfo>, typeResolver: TypeResolver): String {
        this.typeResolver = typeResolver
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by SPIA — do not edit manually.")
        sb.appendLine()

        // Axios import
        if (config.apiClient == ApiClient.AXIOS) {
            sb.appendLine("import type { AxiosInstance } from 'axios';")
            sb.appendLine()
        }

        // ApiError base class — always emitted
        sb.appendLine("/* ──────────── Error Types ──────────── */")
        sb.appendLine()
        sb.appendLine("export class ApiError<T = unknown> extends Error {")
        sb.appendLine("  constructor(public status: number, public data: T, message?: string) { super(message); }")
        sb.appendLine("}")
        sb.appendLine()
        sb.appendLine("export class ApiTimeoutError extends Error {")
        sb.appendLine("  constructor(message?: string) { super(message ?? 'Request timed out'); }")
        sb.appendLine("}")
        sb.appendLine()

        // DTO types section
        val dtos = typeResolver.allDtos()
        val enums = typeResolver.allEnums()
        val generics = typeResolver.allGenerics()
        val sealedUnions = typeResolver.allSealedUnions()
        val valueClasses = typeResolver.allValueClasses()

        if (dtos.isNotEmpty() || enums.isNotEmpty() || generics.isNotEmpty() || sealedUnions.isNotEmpty() || valueClasses.isNotEmpty()) {
            sb.appendLine("/* ──────────── DTO Types ──────────── */")
            sb.appendLine()
        }

        for (enumInfo in enums.sortedBy { it.name }) {
            sb.append(renderEnum(enumInfo))
            sb.appendLine()
        }

        for (valueClass in valueClasses.sortedBy { it.name }) {
            sb.append(renderValueClass(valueClass))
            sb.appendLine()
        }

        // Sealed union subtype DTOs are emitted individually (interfaces), then the union type alias.
        // Track which DTO names were already emitted as part of a sealed union so we skip them in
        // the flat DTO loop (they may also have been registered in resolvedDtos by the resolver).
        val sealedSubtypeDtoNames = sealedUnions.flatMap { it.subtypes.map { s -> s.dto.name } }.toSet()

        for (sealedUnion in sealedUnions.sortedBy { it.name }) {
            sb.append(renderSealedUnion(sealedUnion))
            sb.appendLine()
        }

        for (dto in dtos.filter { it.name !in sealedSubtypeDtoNames }.sortedBy { it.name }) {
            sb.append(renderDto(dto))
            sb.appendLine()
        }

        for (generic in generics.sortedBy { it.name }) {
            sb.append(renderGenericInterface(generic))
            sb.appendLine()
        }

        // Per-endpoint typed error aliases
        val seenAliasNames = mutableSetOf<String>()
        val errorAliases = buildList {
            for (controller in controllers.sortedBy { it.name }) {
                val ns = controllerToNamespace(controller.name)
                for (endpoint in controller.endpoints) {
                    val errorTypes = endpoint.errorResponses.values.toList()
                    if (errorTypes.isEmpty()) continue
                    val baseName = endpoint.functionName.replaceFirstChar { it.uppercase() } + "Error"
                    // Qualify with the controller namespace if the base name is already taken
                    val aliasName = if (baseName !in seenAliasNames) {
                        baseName
                    } else {
                        ns.replaceFirstChar { it.uppercase() } + baseName
                    }
                    seenAliasNames.add(aliasName)
                    val unionTs = if (errorTypes.size == 1) {
                        renderType(errorTypes.first())
                    } else {
                        errorTypes.joinToString(" | ") { renderType(it) }
                    }
                    add("export type $aliasName = ApiError<$unionTs>;")
                }
            }
        }
        if (errorAliases.isNotEmpty()) {
            sb.appendLine("/* ──────────── Endpoint Error Aliases ──────────── */")
            sb.appendLine()
            errorAliases.forEach { sb.appendLine(it) }
            sb.appendLine()
        }

        // API functions section
        if (controllers.isNotEmpty()) {
            sb.appendLine("/* ──────────── API Functions ──────────── */")
            sb.appendLine()
            sb.append(renderCreateApi(controllers))
        }

        return sb.toString()
    }

    /**
     * Emits the shared module containing all DTOs/enums/generics/sealed unions/value classes,
     * the ApiError + ApiTimeoutError classes, and (for fetch) the ClientOptions interface.
     * Per-controller files import from this shared module.
     */
    fun generateShared(controllers: List<ControllerInfo>, typeResolver: TypeResolver): String {
        this.typeResolver = typeResolver
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by SPIA — do not edit manually.")
        sb.appendLine()

        // ApiError base class — always emitted
        sb.appendLine("/* ──────────── Error Types ──────────── */")
        sb.appendLine()
        sb.appendLine("export class ApiError<T = unknown> extends Error {")
        sb.appendLine("  constructor(public status: number, public data: T, message?: string) { super(message); }")
        sb.appendLine("}")
        sb.appendLine()
        sb.appendLine("export class ApiTimeoutError extends Error {")
        sb.appendLine("  constructor(message?: string) { super(message ?? 'Request timed out'); }")
        sb.appendLine("}")
        sb.appendLine()

        if (config.apiClient == ApiClient.FETCH) {
            sb.appendLine("export interface ClientOptions {")
            sb.appendLine("  baseUrl?: string;")
            sb.appendLine("  timeoutMs?: number;")
            sb.appendLine("  authInterceptor?: (request: RequestInit) => RequestInit | Promise<RequestInit>;")
            sb.appendLine("  retry?: { maxAttempts: number; backoffMs: number; retryOn?: (status: number) => boolean };")
            sb.appendLine("}")
            sb.appendLine()
        }

        val dtos = typeResolver.allDtos()
        val enums = typeResolver.allEnums()
        val generics = typeResolver.allGenerics()
        val sealedUnions = typeResolver.allSealedUnions()
        val valueClasses = typeResolver.allValueClasses()

        if (dtos.isNotEmpty() || enums.isNotEmpty() || generics.isNotEmpty() || sealedUnions.isNotEmpty() || valueClasses.isNotEmpty()) {
            sb.appendLine("/* ──────────── DTO Types ──────────── */")
            sb.appendLine()
        }

        for (enumInfo in enums.sortedBy { it.name }) {
            sb.append(renderEnum(enumInfo))
            sb.appendLine()
        }

        for (valueClass in valueClasses.sortedBy { it.name }) {
            sb.append(renderValueClass(valueClass))
            sb.appendLine()
        }

        val sealedSubtypeDtoNames = sealedUnions.flatMap { it.subtypes.map { s -> s.dto.name } }.toSet()

        for (sealedUnion in sealedUnions.sortedBy { it.name }) {
            sb.append(renderSealedUnion(sealedUnion))
            sb.appendLine()
        }

        for (dto in dtos.filter { it.name !in sealedSubtypeDtoNames }.sortedBy { it.name }) {
            sb.append(renderDto(dto))
            sb.appendLine()
        }

        for (generic in generics.sortedBy { it.name }) {
            sb.append(renderGenericInterface(generic))
            sb.appendLine()
        }

        // Per-endpoint typed error aliases — emitted in shared so all controllers can import.
        val seenAliasNames = mutableSetOf<String>()
        val errorAliases = buildList {
            for (controller in controllers.sortedBy { it.name }) {
                val ns = controllerToNamespace(controller.name)
                for (endpoint in controller.endpoints) {
                    val errorTypes = endpoint.errorResponses.values.toList()
                    if (errorTypes.isEmpty()) continue
                    val baseName = endpoint.functionName.replaceFirstChar { it.uppercase() } + "Error"
                    val aliasName = if (baseName !in seenAliasNames) {
                        baseName
                    } else {
                        ns.replaceFirstChar { it.uppercase() } + baseName
                    }
                    seenAliasNames.add(aliasName)
                    val unionTs = if (errorTypes.size == 1) {
                        renderType(errorTypes.first())
                    } else {
                        errorTypes.joinToString(" | ") { renderType(it) }
                    }
                    add("export type $aliasName = ApiError<$unionTs>;")
                }
            }
        }
        if (errorAliases.isNotEmpty()) {
            sb.appendLine("/* ──────────── Endpoint Error Aliases ──────────── */")
            sb.appendLine()
            errorAliases.forEach { sb.appendLine(it) }
            sb.appendLine()
        }

        return sb.toString()
    }

    /**
     * Emits a single per-controller `.api.ts` file. The file imports ApiError /
     * ApiTimeoutError / ClientOptions / all DTO type names from `./_shared` and
     * exports a `create<Controller>Api` factory function that returns the namespace
     * object for that controller.
     */
    fun generateController(
        controller: ControllerInfo,
        typeResolver: TypeResolver,
    ): String {
        this.typeResolver = typeResolver
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by SPIA — do not edit manually.")
        sb.appendLine()

        // Build the type-import list from every declared shared symbol so this file does
        // not need per-controller usage tracking. tsconfig.json in the demo does not set
        // noUnusedLocals, so unused names are tolerated.
        val typeNames = buildList {
            typeResolver.allDtos().forEach { add(it.name) }
            typeResolver.allEnums().forEach { add(it.name) }
            typeResolver.allGenerics().forEach { add(it.name) }
            typeResolver.allSealedUnions().forEach { add(it.name) }
            typeResolver.allValueClasses().forEach { add(it.name) }
        }.toSortedSet()

        when (config.apiClient) {
            ApiClient.AXIOS -> {
                sb.appendLine("import type { AxiosInstance } from 'axios';")
                if (typeNames.isNotEmpty()) {
                    sb.appendLine("import { ApiError, ApiTimeoutError } from './_shared';")
                    sb.appendLine("import type { ${typeNames.joinToString(", ")} } from './_shared';")
                } else {
                    sb.appendLine("import { ApiError, ApiTimeoutError } from './_shared';")
                }
            }
            ApiClient.FETCH -> {
                sb.appendLine("import { ApiError, ApiTimeoutError, type ClientOptions } from './_shared';")
                if (typeNames.isNotEmpty()) {
                    sb.appendLine("import type { ${typeNames.joinToString(", ")} } from './_shared';")
                }
            }
        }
        // Re-export shared symbols so consumers can `import { ApiError, MyDto } from './<slug>.api'` too.
        sb.appendLine("export * from './_shared';")
        sb.appendLine()

        val controllerName = controller.name.removeSuffix("Controller")
        val factoryName = "create" + controllerName.replaceFirstChar { it.uppercase() } + "Api"
        val namespace = controllerToNamespace(controller.name)

        val clientParam = when (config.apiClient) {
            ApiClient.AXIOS -> "client: AxiosInstance"
            ApiClient.FETCH -> "options?: ClientOptions"
        }

        sb.appendLine("export function $factoryName($clientParam) {")
        if (config.apiClient == ApiClient.FETCH) {
            val buildtimeBase = config.baseUrl?.let { "\"${it}\"" } ?: "\"\""
            sb.appendLine("  const _baseUrl = options?.baseUrl ?? $buildtimeBase;")
        }
        sb.appendLine("  return {")
        sb.appendLine("    $namespace: {")

        for (endpoint in controller.endpoints) {
            val fullPath = combinePaths(controller.basePath, endpoint.path)
            sb.append(renderEndpoint(endpoint, fullPath))
        }

        sb.appendLine("    },")
        sb.appendLine("  };")
        sb.appendLine("}")

        return sb.toString()
    }

    /**
     * Emits the index.ts barrel file that re-exports the shared module and every
     * per-controller .api file so consumers can `import { … } from './generated'`.
     */
    fun generateIndex(controllers: List<ControllerInfo>): String {
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by SPIA — do not edit manually.")
        sb.appendLine()
        sb.appendLine("export * from './_shared';")
        for (controller in controllers.sortedBy { it.name }) {
            val slug = controllerToSlug(controller.name)
            sb.appendLine("export * from './$slug.api';")
        }
        return sb.toString()
    }

    /** Returns the kebab-style slug used in per-controller filenames (e.g. UserController -> user). */
    fun controllerToSlug(controllerName: String): String {
        val name = controllerName.removeSuffix("Controller")
        // Convert PascalCase to kebab-case.
        val sb = StringBuilder()
        for ((i, ch) in name.withIndex()) {
            if (ch.isUpperCase() && i > 0) sb.append('-')
            sb.append(ch.lowercaseChar())
        }
        return sb.toString().ifEmpty { "controller" }
    }

    private fun renderEnum(enumInfo: TypeInfo.Enum): String {
        val sb = StringBuilder()
        when (config.enumStyle) {
            EnumStyle.UNION -> {
                val members = enumInfo.constants.joinToString(" | ") { "'$it'" }
                sb.appendLine("export type ${enumInfo.name} = $members;")
            }
            EnumStyle.ENUM -> {
                sb.appendLine("export enum ${enumInfo.name} {")
                for (constant in enumInfo.constants) {
                    sb.appendLine("  $constant = \"$constant\",")
                }
                sb.appendLine("}")
            }
        }
        return sb.toString()
    }

    private fun renderValueClass(valueClass: TypeInfo.ValueClass): String {
        val sb = StringBuilder()
        val underlyingTs = renderType(valueClass.underlying)
        // Branded type: underlying & { readonly __brand: 'Name' }
        sb.appendLine("export type ${valueClass.name} = $underlyingTs & { readonly __brand: '${valueClass.name}' };")
        // Constructor helper: const Name = (raw: underlyingTs): Name => raw as Name
        sb.appendLine("export const ${valueClass.name} = (raw: $underlyingTs): ${valueClass.name} => raw as ${valueClass.name};")
        return sb.toString()
    }

    private fun renderDto(dto: TypeInfo.Dto): String {
        val sb = StringBuilder()
        sb.appendLine("export interface ${dto.name} {")
        for (field in dto.fields) {
            renderField(sb, field)
        }
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderSealedUnion(sealedUnion: TypeInfo.SealedUnion): String {
        val sb = StringBuilder()
        // First emit each subtype's interface definition.
        for (subtype in sealedUnion.subtypes) {
            sb.append(renderDto(subtype.dto))
        }
        // Then emit the union type alias.
        if (sealedUnion.discriminator != null) {
            // Discriminated union: each member is intersected with the literal discriminator object.
            val members = sealedUnion.subtypes.joinToString(" | ") { st ->
                val tag = st.tag ?: st.dto.name
                "({ ${sealedUnion.discriminator}: '${tag}' } & ${st.dto.name})"
            }
            sb.appendLine("export type ${sealedUnion.name} = $members;")
        } else {
            // Nominal union: simple A | B | C without discriminator literals.
            val members = sealedUnion.subtypes.joinToString(" | ") { it.dto.name }
            sb.appendLine("export type ${sealedUnion.name} = $members;")
        }
        return sb.toString()
    }

    private fun renderField(sb: StringBuilder, field: FieldInfo) {
        val hasConstraints = field.constraints.isNotEmpty()
        val hasAliases = field.aliases.isNotEmpty()
        if (hasConstraints || hasAliases) {
            sb.appendLine("  /**")
            if (hasAliases) {
                sb.appendLine("   * @alias ${field.aliases.joinToString(", ")}")
            }
            for (constraint in field.constraints) {
                sb.appendLine("   * @${constraint.keyword} ${constraint.value}")
            }
            sb.appendLine("   */")
        }
        val tsType = renderType(field.type)
        val fieldName = field.serializedName
        when {
            field.type.nullable && field.excludeWhenNull -> sb.appendLine("  $fieldName?: $tsType | null;")
            field.type.nullable -> sb.appendLine("  $fieldName: $tsType | null;")
            else -> sb.appendLine("  $fieldName: $tsType;")
        }
    }

    private fun renderType(type: TypeInfo): String = when (type) {
        is TypeInfo.Primitive -> type.tsType
        is TypeInfo.Array -> "${renderType(type.elementType)}[]"
        is TypeInfo.Record -> {
            val key = renderType(type.keyType)
            val value = renderType(type.valueType)
            "{ [key: $key]: $value }"
        }
        is TypeInfo.Enum -> type.name
        is TypeInfo.Dto -> type.name
        is TypeInfo.Unknown -> type.rawName
        is TypeInfo.Generic -> {
            if (type.typeArguments.isEmpty()) {
                // Raw reference (shouldn't normally happen at usage site, but keep safe).
                "${type.name}<${type.typeParameters.joinToString(", ")}>"
            } else {
                "${type.name}<${type.typeArguments.joinToString(", ") { renderType(it) }}>"
            }
        }
        is TypeInfo.TypeParameter -> type.name
        is TypeInfo.SealedUnion -> type.name
        is TypeInfo.StreamType -> "AsyncIterable<${renderType(type.item)}>"
        is TypeInfo.ValueClass -> type.name
    }

    private fun renderGenericInterface(generic: TypeInfo.Generic): String {
        val sb = StringBuilder()
        val params = generic.typeParameters.joinToString(", ")
        sb.appendLine("export interface ${generic.name}<$params> {")
        for (field in generic.fields) {
            renderField(sb, field)
        }
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderCreateApi(controllers: List<ControllerInfo>): String {
        val sb = StringBuilder()

        val clientParam = when (config.apiClient) {
            ApiClient.AXIOS -> "client: AxiosInstance"
            ApiClient.FETCH -> {
                sb.appendLine("export interface ClientOptions {")
                sb.appendLine("  baseUrl?: string;")
                sb.appendLine("  timeoutMs?: number;")
                sb.appendLine("  authInterceptor?: (request: RequestInit) => RequestInit | Promise<RequestInit>;")
                sb.appendLine("  retry?: { maxAttempts: number; backoffMs: number; retryOn?: (status: number) => boolean };")
                sb.appendLine("}")
                sb.appendLine()
                "options?: ClientOptions"
            }
        }

        sb.appendLine("export function createApi($clientParam) {")
        if (config.apiClient == ApiClient.FETCH) {
            val buildtimeBase = config.baseUrl?.let { "\"${it}\"" } ?: "\"\""
            sb.appendLine("  const _baseUrl = options?.baseUrl ?? $buildtimeBase;")
        }
        sb.appendLine("  return {")

        for (controller in controllers.sortedBy { it.name }) {
            val namespace = controllerToNamespace(controller.name)
            sb.appendLine("    $namespace: {")

            for (endpoint in controller.endpoints) {
                val fullPath = combinePaths(controller.basePath, endpoint.path)
                sb.append(renderEndpoint(endpoint, fullPath))
            }

            sb.appendLine("    },")
        }

        sb.appendLine("  };")
        sb.appendLine("}")
        return sb.toString()
    }

    private fun renderEndpoint(endpoint: EndpointInfo, fullPath: String): String {
        val sb = StringBuilder()

        // Build a JSDoc block combining the source docstring and any @param @default notes
        // for optional @RequestParam values. A non-null defaultValue is Spring's source of
        // truth — we preserve it here without baking it into the SDK signature.
        val jsdocLines = mutableListOf<String>()
        endpoint.jsdoc?.let { jsdocLines += it }
        endpoint.parameters.filter { it.defaultValue != null }.forEach { p ->
            jsdocLines += "@param {${renderType(p.type)}} [${p.name}=${p.defaultValue}] Server default: ${p.defaultValue}"
        }
        if (jsdocLines.isNotEmpty()) {
            sb.appendLine("      /**")
            jsdocLines.forEach { sb.appendLine("       * $it") }
            sb.appendLine("       */")
        }

        val params = renderEndpointParams(endpoint)
        val tsPath = renderEndpointUrl(endpoint, fullPath)
        val promiseType = renderEndpointReturn(endpoint)

        sb.append(renderEndpointCall(endpoint, fullPath, params, tsPath, promiseType, config))

        sb.appendLine()
        return sb.toString()
    }

    /** Builds the TypeScript parameter signature string. */
    private fun renderEndpointParams(endpoint: EndpointInfo): String {
        // Parameter list — optional query params get a TS-level `?` marker so callers
        // may omit them; fetch/axios builders will skip undefined values below.
        // MULTIPART params get File | Blob (single) or (File | Blob)[] (list) types.
        // MODEL_ATTRIBUTE DTOs are flattened to individual fields in the signature.
        // COOKIE params are collected into a single `cookies?: Record<string, string>` opt.
        // MATRIX_VARIABLE params are treated like query string params.
        // REQUEST_ATTRIBUTE params are server-side only and excluded (already filtered by analyzer).
        val parts = mutableListOf<String>()
        var hasCookieParam = false

        for (param in endpoint.parameters) {
            when (param.kind) {
                ParameterKind.MULTIPART -> {
                    val tsType = if (param.type is TypeInfo.Array) "(File | Blob)[]" else "File | Blob"
                    parts.add("${param.name}: $tsType")
                }
                ParameterKind.MODEL_ATTRIBUTE -> {
                    // Flatten DTO fields into individual query-string-style params
                    val dtoFields = resolveDtoFields(param.type)
                    if (dtoFields.isNotEmpty()) {
                        for (field in dtoFields) {
                            val fieldTsType = renderType(field.type)
                            val marker = if (field.type.nullable) "?" else ""
                            parts.add("${field.serializedName}$marker: $fieldTsType")
                        }
                    } else {
                        parts.add("${param.name}: ${renderType(param.type)}")
                    }
                }
                ParameterKind.COOKIE -> {
                    // Collect all @CookieValue params into a single cookies? opt — only add once
                    if (!hasCookieParam) {
                        parts.add("cookies?: Record<string, string>")
                        hasCookieParam = true
                    }
                }
                ParameterKind.REQUEST_ATTRIBUTE -> {
                    // Server-side only — excluded from TS signature; warn callers
                    logger?.warn("@RequestAttribute parameter '${param.name}' is server-side only and is excluded from the generated TypeScript SDK.")
                }
                ParameterKind.MATRIX_VARIABLE -> {
                    // Treat as query string
                    val marker = if (!param.required) "?" else ""
                    parts.add("${param.name}$marker: ${renderType(param.type)}")
                }
                ParameterKind.PAGEABLE -> {
                    // Expand Pageable into three optional inline query fields
                    parts.add("page?: number")
                    parts.add("size?: number")
                    parts.add("sort?: string")
                }
                ParameterKind.QUERY -> {
                    val marker = if (!param.required) "?" else ""
                    parts.add("${param.name}$marker: ${renderType(param.type)}")
                }
                else -> {
                    parts.add("${param.name}: ${renderType(param.type)}")
                }
            }
        }
        // Always append signal?: AbortSignal as the last optional parameter
        parts.add("signal?: AbortSignal")
        return parts.joinToString(", ")
    }

    /**
     * Resolves the DTO fields for a MODEL_ATTRIBUTE parameter type.
     * Returns an empty list if the type is not a known DTO.
     */
    private fun resolveDtoFields(type: TypeInfo): List<FieldInfo> {
        if (type !is TypeInfo.Dto) return emptyList()
        return typeResolver?.allDtos()?.firstOrNull { it.name == type.name }?.fields ?: type.fields
    }

    /** Assembles the axios-style URL template literal with path variable substitutions. */
    private fun renderEndpointUrl(endpoint: EndpointInfo, fullPath: String): String {
        val pathVariables = endpoint.parameters.filter { it.kind == ParameterKind.PATH }
        return buildTsPath(fullPath, pathVariables)
    }

    /** Emits the axios or fetch call line(s) for the endpoint. */
    private fun renderEndpointCall(
        endpoint: EndpointInfo,
        fullPath: String,
        params: String,
        tsPath: String,
        promiseType: String,
        config: SdkConfig,
    ): String {
        val sb = StringBuilder()
        val multipartParams = endpoint.parameters.filter { it.kind == ParameterKind.MULTIPART }
        val bodyParam = endpoint.parameters.firstOrNull { it.kind == ParameterKind.BODY }
        val queryParams = endpoint.parameters.filter { it.kind == ParameterKind.QUERY }
        val headerParams = endpoint.parameters.filter { it.kind == ParameterKind.HEADER }
        val cookieParams = endpoint.parameters.filter { it.kind == ParameterKind.COOKIE }
        val modelAttributeParams = endpoint.parameters.filter { it.kind == ParameterKind.MODEL_ATTRIBUTE }
        val matrixVariableParams = endpoint.parameters.filter { it.kind == ParameterKind.MATRIX_VARIABLE }
        val pageableParams = endpoint.parameters.filter { it.kind == ParameterKind.PAGEABLE }

        // MODEL_ATTRIBUTE, MATRIX_VARIABLE, and PAGEABLE params are expanded into query string fields
        val expandedQueryParams: List<ParameterInfo> = queryParams +
            matrixVariableParams +
            pageableParams.flatMap {
                listOf(
                    ParameterInfo(name = "page", type = TypeInfo.Primitive("number"), kind = ParameterKind.QUERY, required = false),
                    ParameterInfo(name = "size", type = TypeInfo.Primitive("number"), kind = ParameterKind.QUERY, required = false),
                    ParameterInfo(name = "sort", type = TypeInfo.Primitive("string"), kind = ParameterKind.QUERY, required = false),
                )
            } +
            modelAttributeParams.flatMap { p ->
                val fields = resolveDtoFields(p.type)
                if (fields.isNotEmpty()) {
                    fields.map { f ->
                        ParameterInfo(
                            name = f.serializedName,
                            type = f.type,
                            kind = ParameterKind.QUERY,
                            required = !f.type.nullable,
                        )
                    }
                } else {
                    listOf(p.copy(kind = ParameterKind.QUERY))
                }
            }

        // All header-like params: explicit @RequestHeader + cookie header built from @CookieValue params
        val allHeaderParams: List<ParameterInfo> = headerParams +
            if (cookieParams.isNotEmpty()) {
                listOf(
                    ParameterInfo(
                        name = "cookies",
                        type = TypeInfo.Primitive("Record<string, string>"),
                        kind = ParameterKind.HEADER,
                        required = false,
                        headerName = "__cookies__",
                    )
                )
            } else emptyList()

        when (config.apiClient) {
            ApiClient.AXIOS -> {
                if (multipartParams.isNotEmpty()) {
                    // Multipart: emit function body with FormData construction
                    sb.append("      ${endpoint.functionName}: async ($params): Promise<$promiseType> => {\n")
                    sb.appendLine("        const formData = new FormData();")
                    for (mp in multipartParams) {
                        val fieldName = mp.headerName ?: mp.name
                        if (mp.type is TypeInfo.Array) {
                            sb.appendLine("        ${mp.name}.forEach(f => formData.append('$fieldName', f));")
                        } else {
                            sb.appendLine("        formData.append('$fieldName', ${mp.name});")
                        }
                    }
                    val axiosConfig = buildAxiosConfig(expandedQueryParams, headerParams, cookieParams, withSignal = true)
                    sb.appendLine("        return client.${endpoint.httpMethod.name.lowercase()}($tsPath, formData$axiosConfig).then(r => r.data);")
                    sb.appendLine("      },")
                } else {
                    sb.append("      ${endpoint.functionName}: ($params): Promise<$promiseType> =>\n")
                    val axiosConfig = buildAxiosConfig(expandedQueryParams, headerParams, cookieParams, withSignal = true)
                    when (endpoint.httpMethod) {
                        HttpMethod.GET, HttpMethod.DELETE -> {
                            sb.appendLine("        client.${endpoint.httpMethod.name.lowercase()}($tsPath$axiosConfig).then(r => r.data),")
                        }
                        HttpMethod.POST, HttpMethod.PUT, HttpMethod.PATCH -> {
                            val bodyArg = bodyParam?.name ?: "undefined"
                            sb.appendLine("        client.${endpoint.httpMethod.name.lowercase()}($tsPath, $bodyArg$axiosConfig).then(r => r.data),")
                        }
                    }
                }
            }
            ApiClient.FETCH -> {
                sb.append("      ${endpoint.functionName}: async ($params): Promise<$promiseType> => {\n")
                val (queryPrelude, queryFragment) = buildFetchQuery(expandedQueryParams)
                val pathVariables = endpoint.parameters.filter { it.kind == ParameterKind.PATH }
                val fetchPathBase = buildFetchPath(fullPath, pathVariables)
                // Drop the trailing backtick, append the query fragment, re-close the template literal.
                val fetchUrl = if (queryFragment.isNotEmpty()) {
                    fetchPathBase.trimEnd('`') + queryFragment + "`"
                } else fetchPathBase

                for (line in queryPrelude) {
                    sb.appendLine("        $line")
                }

                // Build combined headers: @RequestHeader + Cookie header from @CookieValue params
                fun buildFetchHeaderEntries(): String {
                    val entries = mutableListOf<String>()
                    for (p in headerParams) {
                        val key = p.headerName ?: p.name
                        entries.add("'$key': ${p.name}")
                    }
                    if (cookieParams.isNotEmpty()) {
                        entries.add("'Cookie': Object.entries(cookies ?? {}).map(([k, v]) => `\${k}=\${v}`).join('; ')")
                    }
                    return entries.joinToString(", ")
                }

                val hasFetchHeaders = headerParams.isNotEmpty() || cookieParams.isNotEmpty()

                // Timeout + AbortSignal setup
                sb.appendLine("        const __timeoutMs = options?.timeoutMs;")
                sb.appendLine("        const __controller = new AbortController();")
                sb.appendLine("        let __timeoutId: ReturnType<typeof setTimeout> | undefined;")
                sb.appendLine("        if (__timeoutMs !== undefined) {")
                sb.appendLine("          __timeoutId = setTimeout(() => __controller.abort(new ApiTimeoutError()), __timeoutMs);")
                sb.appendLine("        }")
                sb.appendLine("        const __signals = [__controller.signal, ...(signal ? [signal] : [])];")
                sb.appendLine("        const __signal = __signals.length > 1 ? AbortSignal.any(__signals) : __controller.signal;")
                // Retry + auth configuration — defaults: maxAttempts=0 (off), backoffMs=200, retryOn=status>=500
                sb.appendLine("        const __maxAttempts = options?.retry?.maxAttempts ?? 0;")
                sb.appendLine("        const __backoffMs = options?.retry?.backoffMs ?? 200;")
                sb.appendLine("        const __retryOn = options?.retry?.retryOn ?? ((s: number) => s >= 500);")
                sb.appendLine("        let __attempt = 0;")
                sb.appendLine("        // eslint-disable-next-line no-constant-condition")
                sb.appendLine("        while (true) {")

                if (multipartParams.isNotEmpty()) {
                    // Multipart: build FormData and use as body (no Content-Type — browser sets boundary)
                    sb.appendLine("          const formData = new FormData();")
                    for (mp in multipartParams) {
                        val fieldName = mp.headerName ?: mp.name
                        if (mp.type is TypeInfo.Array) {
                            sb.appendLine("          ${mp.name}.forEach(f => formData.append('$fieldName', f));")
                        } else {
                            sb.appendLine("          formData.append('$fieldName', ${mp.name});")
                        }
                    }
                    if (hasFetchHeaders) {
                        val headerEntries = buildFetchHeaderEntries()
                        sb.appendLine("          let __req: RequestInit = { method: '${endpoint.httpMethod.name}', headers: { $headerEntries }, body: formData, signal: __signal };")
                    } else {
                        sb.appendLine("          let __req: RequestInit = { method: '${endpoint.httpMethod.name}', body: formData, signal: __signal };")
                    }
                } else {
                    when (endpoint.httpMethod) {
                        HttpMethod.GET, HttpMethod.DELETE -> {
                            if (hasFetchHeaders) {
                                val headerEntries = buildFetchHeaderEntries()
                                sb.appendLine("          let __req: RequestInit = { method: '${endpoint.httpMethod.name}', headers: { $headerEntries }, signal: __signal };")
                            } else {
                                sb.appendLine("          let __req: RequestInit = { method: '${endpoint.httpMethod.name}', signal: __signal };")
                            }
                        }
                        HttpMethod.POST, HttpMethod.PUT, HttpMethod.PATCH -> {
                            val bodyArg = bodyParam?.name ?: "undefined"
                            if (hasFetchHeaders) {
                                val headerEntries = buildFetchHeaderEntries()
                                sb.appendLine("          let __req: RequestInit = { method: '${endpoint.httpMethod.name}', headers: { 'Content-Type': 'application/json', $headerEntries }, body: JSON.stringify($bodyArg), signal: __signal };")
                            } else {
                                sb.appendLine("          let __req: RequestInit = { method: '${endpoint.httpMethod.name}', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify($bodyArg), signal: __signal };")
                            }
                        }
                    }
                }
                // Apply authInterceptor before fetch (supports async token refresh)
                sb.appendLine("          if (options?.authInterceptor) __req = await options.authInterceptor(__req);")
                sb.appendLine("          try {")
                sb.appendLine("            const res = await fetch($fetchUrl, __req);")
                sb.appendLine("            if (!res.ok) throw new ApiError(res.status, await res.json(), `SPIA ${endpoint.httpMethod.name} \${res.url} failed: \${res.status} \${res.statusText}`);")
                if (promiseType != "void") {
                    sb.appendLine("            clearTimeout(__timeoutId);")
                    sb.appendLine("            return res.json();")
                } else {
                    sb.appendLine("            clearTimeout(__timeoutId);")
                    sb.appendLine("            return;")
                }
                sb.appendLine("          } catch (error) {")
                // Abort errors from timeout should be re-thrown as ApiTimeoutError
                sb.appendLine("            if (error instanceof Error && error.name === 'AbortError') {")
                sb.appendLine("              clearTimeout(__timeoutId);")
                sb.appendLine("              throw new ApiTimeoutError();")
                sb.appendLine("            }")
                // P-04: catch ApiError specifically (not base Error), use error.status to decide retry
                // 503 → retry (status >= 500 by default), 400 → no retry (status < 500)
                sb.appendLine("            if (error instanceof ApiError && __retryOn(error.status) && __attempt < __maxAttempts) {")
                sb.appendLine("              __attempt++;")
                sb.appendLine("              await new Promise(r => setTimeout(r, __backoffMs));")
                sb.appendLine("            } else {")
                sb.appendLine("              clearTimeout(__timeoutId);")
                sb.appendLine("              throw error;")
                sb.appendLine("            }")
                sb.appendLine("          }")
                sb.appendLine("        }")
                sb.appendLine("      },")
            }
        }
        return sb.toString()
    }

    /** Returns the Promise return type string for the endpoint. */
    private fun renderEndpointReturn(endpoint: EndpointInfo): String {
        val returnTs = renderType(endpoint.returnType)
        return if (returnTs == "void") "void" else returnTs
    }

    private fun buildTsPath(path: String, pathVariables: List<ParameterInfo>): String {
        if (pathVariables.isEmpty()) return "`$path`"
        var tsPath = path
        for (pv in pathVariables) {
            tsPath = Regex("\\{${Regex.escape(pv.name)}(?::[^}]+)?\\}").replace(tsPath) {
                "\${encodeURIComponent(String(${pv.name}))}"
            }
        }
        return "`$tsPath`"
    }

    private fun buildFetchPath(path: String, pathVariables: List<ParameterInfo>): String {
        var tsPath = path
        for (pv in pathVariables) {
            tsPath = Regex("\\{${Regex.escape(pv.name)}(?::[^}]+)?\\}").replace(tsPath) {
                "\${encodeURIComponent(String(${pv.name}))}"
            }
        }
        return "`\${_baseUrl}$tsPath`"
    }

    private fun buildAxiosConfig(
        queryParams: List<ParameterInfo>,
        headerParams: List<ParameterInfo>,
        cookieParams: List<ParameterInfo> = emptyList(),
        withSignal: Boolean = false,
    ): String {
        // axios serializes the params object itself — no manual encoding needed here.
        // Optional params are spread conditionally so an explicit `undefined` is dropped
        // from the outgoing query entirely rather than serialized as "undefined".
        val parts = mutableListOf<String>()
        if (queryParams.isNotEmpty()) {
            val queryParts = queryParams.joinToString(", ") { p ->
                if (p.required) "${p.name}: ${p.name}"
                else "...(${p.name} !== undefined ? { ${p.name}: ${p.name} } : {})"
            }
            parts.add("params: { $queryParts }")
        }
        val allHeaderEntries = mutableListOf<String>()
        for (p in headerParams) {
            val key = p.headerName ?: p.name
            allHeaderEntries.add("'$key': ${p.name}")
        }
        if (cookieParams.isNotEmpty()) {
            allHeaderEntries.add("'Cookie': Object.entries(cookies ?? {}).map(([k, v]) => `\${k}=\${v}`).join('; ')")
        }
        if (allHeaderEntries.isNotEmpty()) {
            parts.add("headers: { ${allHeaderEntries.joinToString(", ")} }")
        }
        if (withSignal) {
            // Pass per-call signal: signal and config.timeout (via axios instance config or options.timeoutMs).
            parts.add("signal: signal")
            parts.add("timeout: undefined") // caller may override via axios instance defaults
        }
        if (parts.isEmpty()) return ""
        return ", { ${parts.joinToString(", ")} }"
    }

    /**
     * Returns (preludeLines, urlFragment) for the fetch query string.
     * - No params: empty list + empty fragment.
     * - All required: inline `?k=${encodeURIComponent(...)}&...` fragment, no prelude.
     * - Has optional: emit `const params = new URLSearchParams(); …; const qs = params.toString();`
     *   as prelude and use `${qs ? `?${qs}` : ''}` as the fragment so all-undefined calls
     *   produce a clean URL with no trailing `?`.
     */
    private fun buildFetchQuery(queryParams: List<ParameterInfo>): Pair<List<String>, String> {
        if (queryParams.isEmpty()) return emptyList<String>() to ""
        val hasOptional = queryParams.any { !it.required }
        if (!hasOptional) {
            val inline = queryParams.joinToString("&") {
                "${encodeURIComponentLiteral(it.name)}=\${encodeURIComponent(String(${it.name}))}"
            }
            return emptyList<String>() to "?$inline"
        }
        val prelude = buildList {
            add("const params = new URLSearchParams();")
            queryParams.forEach { p ->
                if (p.required) {
                    add("params.append('${p.name}', String(${p.name}));")
                } else {
                    add("if (${p.name} !== undefined) params.append('${p.name}', String(${p.name}));")
                }
            }
            add("const qs = params.toString();")
        }
        return prelude to "\${qs ? `?\${qs}` : ''}"
    }

    private fun encodeURIComponentLiteral(name: String): String =
        java.net.URLEncoder.encode(name, Charsets.UTF_8)
            .replace("+", "%20")

    private fun combinePaths(base: String, path: String): String {
        val normalizedBase = base.trimEnd('/')
        val normalizedPath = path.trimStart('/')
        return if (normalizedPath.isEmpty()) normalizedBase
        else "$normalizedBase/$normalizedPath"
    }

    private fun controllerToNamespace(controllerName: String): String {
        val name = controllerName.removeSuffix("Controller")
        return name.replaceFirstChar { it.lowercase() }
    }
}
