package io.spia.processor

import io.spia.processor.model.FieldInfo
import io.spia.processor.model.TypeInfo

/**
 * Generates a `*.zod.ts` sidecar file containing Zod schema definitions for all
 * collected DTOs and generic types.
 *
 * Constraint keyword mapping (from TypeResolver / Bean Validation):
 *   "minLength"  → `.min(value)`        (from @Size.min)
 *   "maxLength"  → `.max(value)`        (from @Size.max)
 *   "minimum"    → `.min(value)`        (from @Min)
 *   "maximum"    → `.max(value)`        (from @Max)
 *   "pattern"    → `.regex(new RegExp("value"))` (from @Pattern)
 *   "format"/"email" → `.email()`       (from @Email)
 *   "notEmpty"   → `.nonempty()`        (from @NotBlank / @NotEmpty on strings)
 * Nullable fields get `.nullable()` appended.
 */
class ZodSchemaGenerator {

    fun generate(dtos: Collection<TypeInfo.Dto>, generics: Collection<TypeInfo.Generic>): String {
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by SPIA — do not edit manually.")
        sb.appendLine()
        sb.appendLine("import { z } from 'zod';")
        sb.appendLine()

        // Emit generic schemas first (they may be referenced by DTOs)
        for (generic in generics.sortedBy { it.name }) {
            sb.append(renderGenericSchema(generic))
            sb.appendLine()
        }

        for (dto in dtos.sortedBy { it.name }) {
            sb.append(renderDtoSchema(dto))
            sb.appendLine()
        }

        return sb.toString()
    }

    private fun renderDtoSchema(dto: TypeInfo.Dto): String {
        val sb = StringBuilder()
        sb.appendLine("export const ${dto.name}Schema = z.object({")
        for (field in dto.fields) {
            sb.appendLine("  ${field.serializedName}: ${renderFieldSchema(field)},")
        }
        sb.appendLine("});")
        sb.appendLine("export type ${dto.name}Schema = z.infer<typeof ${dto.name}Schema>;")
        return sb.toString()
    }

    private fun renderGenericSchema(generic: TypeInfo.Generic): String {
        // For generic types, emit a schema factory function
        val typeParams = generic.typeParameters.joinToString(", ") { "z_$it: z.ZodTypeAny" }
        val sb = StringBuilder()
        sb.appendLine("export const ${generic.name}Schema = ($typeParams) => z.object({")
        for (field in generic.fields) {
            sb.appendLine("  ${field.serializedName}: ${renderFieldSchema(field, generic.typeParameters)},")
        }
        sb.appendLine("});")
        return sb.toString()
    }

    private fun renderFieldSchema(field: FieldInfo, typeParams: List<String> = emptyList()): String {
        var schema = renderTypeSchema(field.type, typeParams)

        // Apply constraints
        for (constraint in field.constraints) {
            schema = applyConstraint(schema, constraint, field.type)
        }

        // Nullable
        if (field.type.nullable) {
            schema = "$schema.nullable()"
        }

        return schema
    }

    private fun applyConstraint(schema: String, constraint: Constraint, type: TypeInfo): String {
        return when (constraint.keyword) {
            "minLength" -> "$schema.min(${constraint.value})"
            "maxLength" -> "$schema.max(${constraint.value})"
            "minimum" -> "$schema.min(${constraint.value})"
            "maximum" -> "$schema.max(${constraint.value})"
            "pattern" -> {
                val escaped = escapeRegexForTs(constraint.value?.toString() ?: "")
                "$schema.regex(new RegExp(\"$escaped\"))"
            }
            "format" -> {
                if (constraint.value?.toString() == "email") "$schema.email()" else schema
            }
            "notEmpty" -> "$schema.nonempty()"
            else -> schema
        }
    }

    private fun escapeRegexForTs(pattern: String): String {
        // Escape backslashes and double-quotes for embedding in a JS string literal
        return pattern.replace("\\", "\\\\").replace("\"", "\\\"")
    }

    private fun renderTypeSchema(type: TypeInfo, typeParams: List<String> = emptyList()): String {
        return when (type) {
            is TypeInfo.Primitive -> renderPrimitiveSchema(type.tsType)
            is TypeInfo.Array -> "z.array(${renderTypeSchema(type.elementType, typeParams)})"
            is TypeInfo.Record -> "z.record(${renderTypeSchema(type.valueType, typeParams)})"
            is TypeInfo.Enum -> "z.string()"
            is TypeInfo.Dto -> "z.lazy(() => ${type.name}Schema)"
            is TypeInfo.Generic -> "z.lazy(() => ${type.name}Schema)"
            is TypeInfo.TypeParameter -> {
                // Reference to a type parameter — use the corresponding z_ variable
                if (type.name in typeParams) "z_${type.name}" else "z.unknown()"
            }
            is TypeInfo.SealedUnion -> "z.unknown()"
            is TypeInfo.StreamType -> "z.unknown()"
            is TypeInfo.ValueClass -> renderTypeSchema(type.underlying, typeParams)
            is TypeInfo.Unknown -> "z.unknown()"
        }
    }

    private fun renderPrimitiveSchema(tsType: String): String {
        return when (tsType.lowercase()) {
            "string" -> "z.string()"
            "number" -> "z.number()"
            "boolean" -> "z.boolean()"
            "bigint" -> "z.bigint()"
            "null" -> "z.null()"
            "undefined" -> "z.undefined()"
            "void" -> "z.void()"
            else -> "z.unknown()"
        }
    }
}
